"""Standalone SIRI consumer package."""

try:
    from siriconsumer.version import __version__
except ImportError:  # generated by setuptools_scm during build/install
    __version__ = "0.0.0"

__all__ = ["__version__"]
