from __future__ import annotations

from contextlib import asynccontextmanager

import uvicorn
from fastapi import FastAPI

from siriconsumer.api.communication import router as communication_router
from siriconsumer.api.control import router as control_router
from siriconsumer.api.dependencies import AppServices
from siriconsumer.api.health import router as health_router
from siriconsumer.api.siri import router as siri_router
from siriconsumer.config import Settings
from siriconsumer.infrastructure.file_spool import FileDurableSpool
from siriconsumer.infrastructure.siri_http_client import SiriHttpClient
from siriconsumer.infrastructure.sqlite_repository import SqliteSubscriptionRepository
from siriconsumer.logging_config import configure_logging
from siriconsumer.services.communication_monitor import LiveCommunicationMonitor
from siriconsumer.services.delivery_admission import DeliveryAdmissionController
from siriconsumer.services.delivery_service import DeliveryService
from siriconsumer.services.fetched_delivery_service import FetchedDeliveryService
from siriconsumer.services.provider_monitor import ProviderMonitor
from siriconsumer.services.sink_worker import SinkWorkerPool
from siriconsumer.services.subscription_manager import SubscriptionManager
from siriconsumer.sinks.factory import DefaultSinkFactory

try:
    from siriconsumer.version import __version__
except ImportError:  # version.py is generated by setuptools_scm during build/install
    __version__ = "0.0.0"

settings = Settings()
configure_logging(settings.log_level)


@asynccontextmanager
async def lifespan(app: FastAPI):
    settings.state_dir.mkdir(parents=True, exist_ok=True)

    repository = SqliteSubscriptionRepository(str(settings.database_path))
    communication_monitor = LiveCommunicationMonitor()

    siri_client = SiriHttpClient(
        settings.provider_request_timeout_seconds,
        communication_monitor=communication_monitor,
    )
    spool = FileDurableSpool(
        settings.spool_path,
        max_messages_per_subscription=settings.spool_max_messages_per_subscription,
    )

    sink_factory = DefaultSinkFactory()
    delivery_admission = DeliveryAdmissionController()

    subscription_manager = SubscriptionManager(
        repository, siri_client, spool, sink_factory, delivery_admission
    )

    delivery_service = DeliveryService(repository, spool, delivery_admission)
    fetched_delivery_service = FetchedDeliveryService(
        repository,
        siri_client,
        delivery_service,
        max_more_data_requests=settings.fetched_delivery_max_more_data_requests,
    )

    provider_monitor = ProviderMonitor(
        settings, repository, siri_client, subscription_manager
    )

    sink_workers = SinkWorkerPool(settings, spool, repository, sink_factory)

    services = AppServices(
        repository=repository,
        communication_monitor=communication_monitor,
        siri_client=siri_client,
        spool=spool,
        sink_factory=sink_factory,
        subscription_manager=subscription_manager,
        delivery_service=delivery_service,
        fetched_delivery_service=fetched_delivery_service,
        provider_monitor=provider_monitor,
        sink_workers=sink_workers,
    )
    app.state.services = services
    app.state.settings = settings

    await repository.initialize()
    await spool.initialize()
    await sink_workers.start()
    await fetched_delivery_service.start()
    await subscription_manager.recover_all_startup()
    await provider_monitor.start()

    try:
        yield
    finally:
        await provider_monitor.stop()
        await fetched_delivery_service.stop()
        await sink_workers.stop()
        await sink_factory.close()
        await siri_client.close()


app = FastAPI(
    title="SIRI Consumer Control API",
    version=__version__,
    description="Standalone SIRI subscription consumer and durable delivery forwarder.",
    docs_url="/api/swagger",
    openapi_url="/api/swagger/openapi.json",
    redoc_url=None,
    lifespan=lifespan,
)
app.include_router(control_router)
app.include_router(communication_router)
app.include_router(siri_router)
app.include_router(health_router)


def run() -> None:
    uvicorn.run(
        "siriconsumer.main:app",
        host=settings.host,
        port=settings.port,
    )


if __name__ == "__main__":
    run()
