from __future__ import annotations

from typing import Protocol

from siriconsumer.domain.models import SpoolEntry, SpoolMetadata


class DurableSpool(Protocol):
    async def initialize(self) -> None: ...

    async def put(self, metadata: SpoolMetadata, payload: bytes) -> SpoolEntry: ...

    async def remove(self, entry: SpoolEntry) -> None: ...

    async def purge(self, subscription_ref: str) -> int: ...

    async def wait_until_idle(self, subscription_ref: str) -> None: ...

    async def next_pending(self) -> SpoolEntry: ...

    async def requeue(self, entry: SpoolEntry) -> None: ...

    async def record_retry(self, entry: SpoolEntry) -> int: ...

    def pending_count(self, subscription_ref: str) -> int: ...
